### ISSUE TITLE
Bug: "UnboundLocalError: local variable 'info' referenced before assignment". Problem with terminal local language

### ISSUE THREAD

**Issue by maelmadon** [cxreet/razor#3]
Hi,
While trying to make RAZOR work on the bzip2, I experimented a bug.

### Bug report
```
mael:bzip2-1.0.5$ py run_razor.py debloat
[...]
running  python ../../../stitcher/src/find_symbols.py ./bzip2.orig ./instr.s > ./callbacks.txt
Traceback (most recent call last):
  File "../../../stitcher/src/find_symbols.py", line 182, in <module>
    main()
  File "../../../stitcher/src/find_symbols.py", line 177, in main
    find_symbols_for_plt(orig_bin_path, orig_asm_path)
  File "../../../stitcher/src/find_symbols.py", line 65, in find_symbols_for_plt
    got_addr = eb.read_dynamic_option(binname, DYNAMIC.DT_PLTGOT)
  File "/media/documents/Documents/Cours/master_thesis/razor/stitcher/src/elf_basic.py", line 400, in read_dynamic_option
    dyn_offset, dyn_infile_size = self.get_dynamic_offset_size(binname)
  File "/media/documents/Documents/Cours/master_thesis/razor/stitcher/src/elf_basic.py", line 331, in get_dynamic_offset_size
    phdr_num = self.get_elfhdr_info(binname, "Number of program headers:");
  File "/media/documents/Documents/Cours/master_thesis/razor/stitcher/src/elf_basic.py", line 110, in get_elfhdr_info
    return info
UnboundLocalError: local variable 'info' referenced before assignment
```

It appeared that the problem was the language of my terminal which was set to french, issuing bad mapping when running the command `readelf -h` through `os.popen()` from the file `get_elfhdr_info`.

### Workaround
I could circumvent this problem by changing my local language before running RAZOR:
`LANGUAGE=en_US.utf_8 python run_razor.py debloat`
However, something could be added in the program to ensure that. Not sure what is the best way though...

**Comment by cxreet** [comment]
Hi @Mema5 , please use our docker image to try running the benchmarks. We may add the encoding checks later to avoid this problem.
